name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run the workflow manually from the GitHub Actions tab 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # ----------------------------------------------------------------------
      # CRITICAL CHANGE: Use 'generate' and set Base URL
      # If your repo is NOT 'username.github.io', this step is MANDATORY.
      # It sets asset paths correctly for project pages (e.g., /repo-name/asset.js).
      # If your repository is 'weizhengliang.github.io', change this line to:
      # run: pnpm run generate
      # ----------------------------------------------------------------------
      - name: Build and Generate Static Site
        # The NUXT_APP_BASE_URL is dynamically set to the repository name.
        # Example: if repo is 'personal-site', base URL becomes /personal-site/
        run: pnpm run generate

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Tell GitHub Pages where to find the static files
          static_site_generator: custom
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Nuxt 3 output directory for static files
          path: .output/public

  deploy:
    environment:
      name: github-pages
    # The URL will be set by the deploy action itself
    url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
